### ISSUE TITLE
Add missing team members/ pics

### ISSUE THREAD

**Issue by amitaibu** [Gizra/gizra.com#339]
* [ ] @kazabooboo (Adar)
* [x] @nirgn975 
* [ ] @Moo64c 

folks, if you are not in the office, please take your own picture, similar to how @IshaDakota [did it](https://github.com/Gizra/Gizra/pull/335).

**Comment by IshaDakota** [comment]
> have you the phone's camera for that or a real camera?

I tried with a phone, but I had to get a real photographer to take it to have it match up nicely. She shot it with a plain black backdrop, which doesn't exactly match the other photos, but it's close enough.

The main thing is that they need to shoot from the waist up and leave enough space above your head so that the proportion is the same as the other pictures. I actually needed to photoshop some space in to get it right.

**Comment by kazabooboo** [comment]
@IshaDakota - litte like Zelig but not a bad at all... I will work on it this weekend with a friend photographer

**Comment by DavidKohav** [comment]
Hi @bricel - Can we update the team members/ pics?

**Comment by bricel** [comment]
@DavidKohav I think @guytepper is working on this, but you you'r well come to do it too.

**Comment by DavidKohav** [comment]
I will check with him, and update.

**Comment by DavidKohav** [comment]
@bricel - Do you have the images?

**Comment by bricel** [comment]
here https://drive.google.com/drive/u/0/folders/0BykxrQzqJoUTZlB0czdXQ0ZUQXM
This include the pictures we need to update too.

**Comment by DavidKohav** [comment]
@YaronMiro - 
Can you please help me with styling the photos?

**Comment by YaronMiro** [comment]
@DavidKohav 
Sure I will help you on Sunday with styling the picutres

**Comment by DavidKohav** [comment]
10X man!

**Comment by DavidKohav** [comment]
Please deploy when you ready.

**Comment by amitaibu** [comment]
@kazabooboo we need to add your pic as-well :)

**Comment by amitaibu** [comment]
closed in favor of #430
